
!ENTRY org.eclipse.egit.ui 4 0 2016-05-17 11:49:42.533
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:222)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:210)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:195)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:206)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:93)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.io.IOException: 另一个程序已锁定文件的一部分，进程无法访问。
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:302)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:100)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:188)
	... 7 more
